.TH DNA4_COUNT_MISMATCHES 3 2019-08-30 "LIBDNA" "LIBDNA"

.SH NAME
dna4_count_mismatches \- count the number of mismatching bytes

.SH SYNOPSIS
.nf
.B #include <kloetzl/dna.h>
.PP
.BI "size_t dna4_count_mismatches(const char *" begin ", const char *" end ", const char *" other ");"
.fi

.SH DESCRIPTION
The \fBdna4_count_mismatches\fR() function efficiently compares two strings and returns the number of mismatching bytes. The first string is delimited by \fIbegin\fR and \fIend\fR (exclusive). For the second string only the start must be supplied via \fIother\fR as it is assumed to be at least as long as the former. 

The result is undefined if the input string contains characters besides
.IR A ,
.IR C ,
.IR G " and"
.IR T .
Lowercase letters are also not allowed. Null bytes are not interpreted as the end of a string.

.SH RETURN VALUE
Returns the number of mismatches.

.SH EXAMPLE
.in +4
.EX
const char seq1[] = "ACGTACGTACGT";
const char seq2[] = "ACGTTCGTACGA";
size_t snps = dna4_count_mismatches(seq1, seq1 + sizeof(seq1) - 1, seq2);

assert(snps == 2);
