.TH DNAX_COUNT 3 2020-06-03 "LIBDNA" "LIBDNA"

.SH NAME
dnax_count \- count characters

.SH SYNOPSIS
.nf
.B #include <dna.h>
.PP
.BI "void dnax_count(size_t *" table ", const char *" begin ", const char *" end ");"
.fi

.SH DESCRIPTION
The \fBdnax_count\fR() function counts the occurences of characters and stores them in the given \fItable\fR. The input string is delimited by \fIbegin\fR and \fIend\fR (exclusive).

.SH EXAMPLE
.in +4
.EX
double gc_content(const char *begin, const char *end)
{
	size_t table[256] = {0};
	dnax_count(table, begin, end);
	double gc = table['G'] + table['C'] + table['g'] + table['c'];
	return gc / (end - begin);
}
