branches:
  except:
    - readthedocs

language: cpp
dist: focal
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install meson ninja-build

script:
- cd $TRAVIS_BUILD_DIR
- mkdir builddir
- meson builddir -Dwith-tests=true
- cd builddir
- ninja
- ninja test
