SHELL=zsh

.PHONY: format

exportedsymbols:
	nm builddir/libdna.so | awk '$$2 ~ /R|T/' > $@

format:
	clang-format -i src/*.h src/*.c include/*.h
	clang-format -i bench/*.cxx
	clang-format -i test/*.cxx
	clang-format -i rttest/*.c rttest/*.c

builddir:
	meson $@

builddir_wtests:
	meson $@ -Dwith-tests=true --buildtype=debugoptimized

builddir_wbench:
	meson $@ -Dwith-benchmarks=true
