SHELL=zsh

.PHONY: clean format

format:
	clang-format -i src/*.h src/*.c include/*.h
	clang-format -i bench/*.cxx
	clang-format -i test/*.cxx

clean:
	$(MAKE) -C src clean
	$(MAKE) -C bench clean
	setopt null_glob; $(RM) -rf *.o dna_test *.a *.so
